### ISSUE TITLE
[Feature💄]: Refactor reset password component.

### ISSUE THREAD

**Issue by wiseaidev** [brave-chat/brave-chat#36]
**👶 Getting Started**
Please [search the history](https://github.com/brave-chat/brave-chat/issues) to see if an issue already exists for the same problem.
- [X] I have searched the existing issues.
- [X] I have tested the latest version.

**📝 Describe the feature**
The current implementation of [`ResetPassword` states](https://github.com/brave-chat/brave-chat/blob/5b009cf45581f26c27e1fa526e22514087420997/src/components/ResetPassword/index.js#L19-L29) component are not following the so-called "Best Practice" or whatever. You can take a look at the [`SignIn` component](https://github.com/brave-chat/brave-chat/blob/5b009cf45581f26c27e1fa526e22514087420997/src/components/SignIn/index.js#L21-L30) after the refactoring process for a guide to how things should look like.

**📸 Screenshots**
Not necessary.

**🔦 Context**
That's it. Good luck!

**Comment by andrewkykoo** [comment]
Hi @wiseaidev, I would like to work on this issue! Thanks.

**Comment by wiseaidev** [comment]
Thanks once again for your contribution!
