### ISSUE TITLE
[Feature💄]: Refactor `EditInfo` component.

### ISSUE THREAD

**Issue by wiseaidev** [brave-chat/brave-chat#37]
**👶 Getting Started**
Please [search the history](https://github.com/brave-chat/brave-chat/issues) to see if an issue already exists for the same problem.
- [X] I have searched the existing issues.
- [X] I have tested the latest version.

**📝 Describe the feature**
The current implementation of the [`EditInfo` states](https://github.com/brave-chat/brave-chat/blob/5b009cf45581f26c27e1fa526e22514087420997/src/components/EditInfo/index.js#L25-L33) component are not following the so-called "Best Practice" or whatever. You can take a look at the [`SignIn` component](https://github.com/brave-chat/brave-chat/blob/5b009cf45581f26c27e1fa526e22514087420997/src/components/SignIn/index.js#L21-L30) after the refactoring process for a guide to how things should look like.

**📸 Screenshots**
Not necessary.

**🔦 Context**
That's it. Good luck!

**Comment by andrewkykoo** [comment]
Hi @wiseaidev, I would like to work on this issue. Thanks.

**Comment by wiseaidev** [comment]
Hey @andrewkykoo, thanks for your interest in this project. Would love to see folks' contributions. Assigned it to you! Good luck!

**Comment by MaverickDe** [comment]
Hi is the issue already assigned to someone?

**Comment by wiseaidev** [comment]
Hey @MaverickDe, Thanks for showing interest in this project. Since #36 was already assigned to @andrewkykoo, I will reassign it to your to emphasize on collaborative work. Sorry about dat, @andrewkykoo; However, You still have an issue to work on, which is similar to this one. Have a nice day/evening, fellas!

**Comment by MaverickDe** [comment]
Thank you. In the Edit component, what exactly are we looking out for when
refactoring , or rather what are the drawbacks that need to be corrected
through refactoring

**Comment by wiseaidev** [comment]
Have a look at what Andrew did in #41.

**Comment by wiseaidev** [comment]
Fixed in #46
